name=NEURGenerator
version=1.2.5
author=mikewap83
maintainer=mikewap83
sentence=Библиотека для генерации изображений через Pollinations.ai API на ESP32-S3
paragraph=Полный цикл: подготовка промптов, перевод, генерация, получение JPEG в PSRAM, callback'и, WDT поддержка
category=Communication
url=https://github.com/mikewap83/NEURGenerator
architectures=esp32
depends=GyverHTTP, GSON, GTimer, ESP32Ping
