name=NEURGenerator
version=1.0.1
author=mikewap83
maintainer=mikewap83
sentence=Библиотека для Pollinations.ai API на ESP32S3 с GyverHTTP и GSON
paragraph=Позволяет проверять баланс Pollen с использованием современных библиотек
category=Communication
url=https://github.com/mikewap83/NEURGenerator
architectures=esp32
depends=GyverHTTP, GSON, GTimer, ESP32Ping
